from tests.vocabulary.vocabulary_read_request_test import VocabularyReadRequestTest
from tests.vocabulary.vocabulary_read_response_test import VocabularyReadResponseTest
from tests.vocabulary.vocabulary_patch_request_test import VocabularyPatchRequestTest
